(defpackage :lisp-chat/tests
  (:use :cl :cl-user :parachute)
  (:local-nicknames (:config :lisp-chat/config)
                    (:server :lisp-chat/server)
                    (:bt :bordeaux-threads)
                    (:usocket :usocket))
  (:import-from :lisp-chat/server :interrupt-thread-portable)
  (:import-from :usocket :socket-connect :socket-close :socket-stream)
  (:import-from :websocket-driver :start-connection :send :on :close-connection)
  (:import-from :websocket-driver-client :make-client)
  (:export :run-tests))
