name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker-lint
        run: make docker-lint

  elisp-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 30.2
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: emacs/*.el
        warnings_as_errors: true

  tests:
    runs-on: ubuntu-latest
    needs: [lint, elisp-check]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image & Run Integration tests
        run: make docker-check

  docker-appimage:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - name: Build Lisp Chat appimage
        run: make docker-appimage